version: '4.0'

actions:


#######################################################
# ethnicity
#######################################################

  generate_dataset_ethnicity:
    run: ehrql:v1 generate-dataset analysis/ethnicity/dataset_definition.py --output output/ethnicity/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/ethnicity/dataset.csv.gz


#######################################################
# PRIMIS
#######################################################

  generate_dataset_PRIMIS:
    run: ehrql:v1 generate-dataset analysis/PRIMIS/dataset_definition.py --output output/PRIMIS/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/PRIMIS/dataset.csv.gz


#######################################################
# vaccine-history
#######################################################

  generate_dataset_vaccine-history:
    run: ehrql:v1 generate-dataset analysis/vaccine-history/dataset_definition.py --output output/vaccine-history/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/vaccine-history/dataset.csv.gz

