version: '4.0'

actions:

#######################################################
# PRIMIS
#######################################################

  generate_dataset_PRIMIS:
    run: ehrql:v1 generate-dataset analysis/PRIMIS/dataset_definition.py --output output/PRIMIS/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/PRIMIS/dataset.csv.gz